# Generated by Django 6.0.3 on 2026-03-09 20:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_id', models.CharField(max_length=16)),
                ('permit_type', models.CharField(max_length=64)),
                ('application_start_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField()),
                ('work_description', models.TextField(blank=True, null=True)),
                ('street_number', models.CharField(max_length=16)),
                ('street_direction', models.CharField(max_length=8)),
                ('street_name', models.CharField(max_length=32)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('community_area_id', models.CharField(max_length=2)),
            ],
        ),
    ]
